### ISSUE TITLE
File download location cannot be set

### ISSUE THREAD

**Issue by PaulVayssiere** [linuxserver/docker-resilio-sync#11]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

**OS: unRaid 6.4.0**

**Command that unRaid runs:**
/usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="resilio-sync" --net="bridge" -e TZ="America/Guatemala" -e HOST_OS="unRAID" -e "PUID"="99" -e "PGID"="100" -p 8888:8888/tcp -p 55555:55555/tcp -v "/mnt/user/Backup/Resilio/":"/sync":rw -v "/mnt/user/CacheShareOnly/resiliocache/":"/cache":rw -v "/mnt/user/appdata/resilio-sync":"/config":rw linuxserver/resilio-sync

**More details with screenshots:**
https://lime-technology.com/forums/topic/51613-support-linuxserverio-resilio-sync/?do=findComment&comment=628389

**If you have a suggestion or fix for the project, please provide us with the following information**
My suggestion is, like gave the possibility to set these folders (from your readme file):

> -v /config - contains the settings
> -v /sync - sync folders root

To add a new one for the /download (maybe being optional if necessary) (I named it "/cache" in my screenshots)

**What you think your suggestion brings to the project, or fixes with the project**
Right now I think all the downloaded files are set to be in the unRaid docker image. If we sync lots of big files at once, I think it might create some sizing issues.

**Comment by PaulVayssiere** [comment]
I don't think it worked :(

I tried to delete completely my image and its config files. I re-created it

I used the command:
> /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="resilio-sync" --net="bridge" -e TZ="America/Guatemala" -e HOST_OS="unRAID" -e "PUID"="99" -e "PGID"="100" -p 8888:8888/tcp -p 55555:55555/tcp -v "/mnt/user/Backup/Resilio/":"/sync":rw -v "/mnt/user/CacheShareOnly/resiliocache/":"/downloads":rw -v "/mnt/user/appdata/resilio-sync":"/config":rw linuxserver/resilio-sync

Which seems good. But when in the UI, it still shows "/root/Resilio Sync" as the file download location. And once again if I save the new location to "/downloads", and stop and start again the image, it still doesn't remember and reset it to "/root/Resilio Sync". At this point I am tempted to do a 
> -v $PATH_TO_CACHE:"/root/Resilio Sync":rw

But I do not know what is this "/root" folder, I don't see it in any configuration file and even less why it keep resetting...

**Comment by sparklyballs** [comment]
it won't have permissions to save anything in /root

there isn't much we can do to mitigate this as the downloads folder setting is not written to any config file which to me is a bug in resilio itself

**Comment by sparklyballs** [comment]
add this line 

`"files_default_path" : "/downloads",`

to /config/sync.conf

below the line

`"directory_root" : "/sync/",`

and it should be persistent

**Comment by PaulVayssiere** [comment]
I saw you commited that so I updated and it worked! Thanks!!
