### ISSUE TITLE
How to add timezone?

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-resilio-sync#14]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

**OS: Unraid 6.4.1**
**Default template settings**

I'd like to add a timezone so I can use the weekly scheduled settings. 
```bash
docker exec -it Sync /bin/bash
date
``` 
The date is about 15 hours ahead.

**Comment by thelamer** [comment]
You need to pass the TZ variable to the container, I will create a pull request to update the readme it should be included: 
IE:
```
-e TZ=US/Eastern
```

**Comment by sparklyballs** [comment]
unraid sets it automatically with dockers

**Comment by sparklyballs** [comment]
you need to check your unraid system timezone because unraid automatically add TZ to the run line of any docker

**Comment by thelamer** [comment]
@sparklyballs tested and created pull request to update the readme, even if this does not directly apply to unraid should be in the readme  no ?

**Comment by ghost** [comment]
>unraid sets it automatically with dockers
you need to check your unraid system timezone because unraid automatically add TZ to the run line of any docker

Is this under Unraid>Settings>DateTime? Because I have it set correctly yet it's not correct in most of my docker containers :( I've checked the host machine's `date` output, and it's correct.

Anyways, thanks for letting me know!

**Comment by ghost** [comment]
I added the appropriate TZ variable, yet it doesn't seem to be the right time, still?

![](https://i.imgur.com/I7DLHN3.png)

**Comment by tobbenb** [comment]
Might be better to open a thread on the unraid forum about this. More people watching there and it also looks like the problem is unraid related.
Post your docker run command, screenshot of date output in both unraid and container and time and date settings of unraid.

**Comment by ghost** [comment]
```bash
docker run -d --name='Sync' --net='bridge' -e TZ="Australia/Perth" -e HOST_OS="unRAID" -p '8888:8888/tcp' -p '5555:5555/tcp' -p '3838:3838/udp' -v '/path/to/volume/':'/path':'rw' -v '/mnt/user/appdata/Sync':'/config':'rw' 'limetech/sync'

The command finished successfully!
```

![](https://i.imgur.com/PiH5tHN.png)
![](https://i.imgur.com/78to9v4.png)

I'll create a thread on the Unraid forum, thanks

edit: was using the wrong container all along.. fixed now.
