### ISSUE TITLE
PUID/PGID variable not used

### ISSUE THREAD

**Issue by jzck** [linuxserver/docker-resilio-sync#17]
I was wondering why all resilio folders were owned by user `abc`, it's obvious when looking the container code that `abc` is in fact hardcoded.

this is misleading when the readme advertises the use of `PUID` and `PGID` environment variables...

**Comment by CHBMB** [comment]
`abc` is just a pseudonym for whatever `PUID` and `PGID` is used.

For instance on my host I use `nobody:users` `99:100` inside the container if I do a `ls -la /config` it will show everything as owned by `abc:abc` but if you check the same mounted folder on the host it will indeed show those same files as being owned by `nobody:users` as designed.
