### ISSUE TITLE
58GB of logs in 21 hours

### ISSUE THREAD

**Issue by nkings10** [linuxserver/docker-resilio-sync#18]
Just having an issue with logs, its happening across 2 unRAID servers and others have also mentioned that the container has caused them issues too due to logs.

I have docker log rotation turned on, i have Resilio logs turned off and am still filling my docker.img file every 24 hours.

<img width="1679" alt="unraid_resilio_size" src="https://user-images.githubusercontent.com/9352121/50972262-e3be6f80-1531-11e9-92ab-f49cbddfd1fa.png">

![image](https://user-images.githubusercontent.com/9352121/50972061-524efd80-1531-11e9-9d79-0812fbaa1fe6.png)

The error i'm currently seeing in the logs is this:
`[20190110 23:43:25.942] assert failed /home/jenkins/slave-root/workspace/Build-Sync-Manually/sync/fs/tree/SyncFileEntryTree.cpp:167`

Is there an issue with the current build or are both my containers for some reason broken?
Happy to do any testing necessary or help in any way to try and resolve the issue.

Thanks,
Nathan

**Comment by j0nnymoe** [comment]
@nkings10 could you try running `docker exec -it Resilio du -shx /` via ssh when connected to your unraid box please? And post the output here.

Cheers

**Comment by nkings10** [comment]
@j0nnymoe 
<img width="371" alt="img" src="https://user-images.githubusercontent.com/9352121/50975116-7feb7500-1538-11e9-80f5-121aaf3ac780.png">

I cleared the logs with a script 2 hours ago and its reporting 2.71GB already.
[This is the script i used](https://snippets.cacher.io/snippet/441df60f22b9bbf937f9)

**Comment by nkings10** [comment]
I just rebuilt my docker image using the same config and its still happening. Could it be something in my config playing up.

**Comment by j0nnymoe** [comment]
Unfortunately we don't have a solution right now, we are going to have to test internally and see if we can replicate this issue.

**Comment by nkings10** [comment]
<img width="1467" alt="nkings10_addcontainer" src="https://user-images.githubusercontent.com/9352121/51028993-cdbbb800-15e0-11e9-8fd8-046af971c78f.png">

I spun up a new container not linking it to my existing appdata and its not throwing the same errors and not filling up the logs.

I'll just set this one up from scratch with my pro license and reconnect to my folders and see what happens.

**Comment by j0nnymoe** [comment]
Ah that's interesting, yes please report back in a couple of days and let us know :)

**Comment by nkings10** [comment]
I spun up a new container image and setup my config from scratch and after a couple of days its back at 50GB+ of logs.

Slightly different errors this time.

![log_for__resilio](https://user-images.githubusercontent.com/9352121/51097884-50c45480-1813-11e9-8aa8-028d42413953.png)

**Comment by aether-smith** [comment]
Can confirm I've been seeing this issue as well for a while. It seemed to disappear for the past couple weeks for me, then suddenly my Docker image was filled up in the space of a day or so.

![log file](https://user-images.githubusercontent.com/9386463/51406383-026ec880-1b27-11e9-86e3-863ddf3a9ce0.png)

![config](https://user-images.githubusercontent.com/9386463/51406409-0e5a8a80-1b27-11e9-8f30-03f18b140f02.png)

**Comment by j0nnymoe** [comment]
Is this still an issue?

**Comment by aether-smith** [comment]
Hasn't appeared for me recently, but I've seen quiet periods before in between incidences of this problem, so I'm not confident in saying it's gone yet.

**Comment by aether-smith** [comment]
Heh, almost as if to answer, this problem flared up again last night.

**Comment by DGalt** [comment]
I just recently set this up on my unRaid server and am now running in to this as well. Is there any way to limit the size of the log?

**Comment by ironicbadger** [comment]
I've had intermittent instances of sync filling up my `/var/lib/docker` partition but then I just delete the image and the problem goes away "for a while".

My best guess here is that there is either a misconfigured path internally to the container which would be a bug for us to fix. Or it's cacheing internally somewhere and this is filling stuff up because 50+gb of logs, well that's quite a lot.

**Comment by aptalca** [comment]
@DGalt see here: https://forums.unraid.net/topic/43549-log-rotation-for-docker-or-limit-log-size/page/3/?tab=comments#comment-587316

**Comment by aptalca** [comment]
Closing for now. If you're still having issues, you can reopen.

**Comment by don4of4** [comment]
Just encountered this as well.  Highly annoying--is there any way the image can be distributed with some tweaks on the default logging?

**Comment by j0nnymoe** [comment]
@don4of4 it would be useful if you could provide information on what's happening in your setup. As you can see from previous comments that we haven't been able to pin point it ourselves.
