### ISSUE TITLE
Doesn't start on RPi Zero W

### ISSUE THREAD

**Issue by tynor88** [linuxserver/docker-resilio-sync#20]
I'm trying to start the docker on RPi Zero W:

I get this:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
**[cont-init.d] 10-adduser: exited 267.**
[cont-init.d] 30-config: executing...
**[cont-init.d] 30-config: exited 267.**
[cont-init.d] done.
[services.d] starting services
[services.d] done.

And it does not write any files to /config. I have it running great on regular RPi 3. But on Zero W i have no way to start it. I tried reinstalling Raspbian (Lite) and reinstalling docker. I also tried chown'ing folder and specifying different PGID and PUID. But same result.

**Comment by CHBMB** [comment]
Clarified [here](https://github.com/linuxserver/docker-ombi/issues/48)
