### ISSUE TITLE
Unraid Docker Icon Update Request.

### ISSUE THREAD

**Issue by chrisallen** [linuxserver/docker-resilio-sync#23]
Could we please have the Docker icon updated that is shown on Unraid to be this?

https://dl2.macupdate.com/images/icons512/47763.png

![image](https://user-images.githubusercontent.com/203867/59492262-b446d100-8edc-11e9-9b32-faa947e2813e.png)

Thanks in advanced.

**Comment by CHBMB** [comment]
@chrisallen You can make a PR to the docker-templates repo, goes in the Img folder.  Just name it the same as the existing file or it'll break our readme and docs.
