### ISSUE TITLE
removing the /sync mount point results in failure to start

### ISSUE THREAD

**Issue by drizuid** [linuxserver/docker-resilio-sync#25]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

A user came into discord and reported an issue where when removing the /sync path completely the container would error continuously. They were using unraid, but i was able to reproduce this using compose. Not mapping the path SHOULD just result in a volume being used, but it causes jenkins issues. I do not see a /sync volume created in the default volume path.

------------------------------

## Expected Behavior
removing /sync's mapping should result in a volume being created and container should run

## Current Behavior
removing /sync's mapping results in continuous jenkins errors (about 10 per second forever) and container will eventually run

## Compose and logs
docker-compose: https://pastebin.com/kb4mm13e
docker logs: https://pastebin.com/Xp6Zx9Ep

## Environment
**OS:**      debian 10
**CPU architecture:** x86_64      
**How docker service was installed:**      debian repo
Docker version 19.03.5, build 633a0ea838
docker-compose version 1.21.0, build unknown

**Comment by thelamer** [comment]
Have you tested a build with /sync defined here https://github.com/linuxserver/docker-resilio-sync/blob/master/Dockerfile#L29 ?

**Comment by drizuid** [comment]
I haven't, i simply pulled this to try and reproduce the issue. I'll give it a shot
