### ISSUE TITLE
support port forwarding by enforcing listen to 0.0.0.0 instead of 127.0.0.1

### ISSUE THREAD

**Issue by malger** [linuxserver/docker-resilio-sync#27]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

The port mapping is ignored since the app listens to 127.0.0.1 instead of 0.0.0.0

FIX: run with ./rslsync --webui.listen 0.0.0.0:8888

------------------------------

## Expected Behavior

The port mapping is should be working.

## Current Behavior

The port mapping is ignored.

## Steps to Reproduce

1. setup a port mapping eg. -p 80:8888
2. start the container
3. the docker container is not responding to port 80

## Environment
**OS:**  debian   
**CPU architecture:** arm64      
**How docker service was installed:**      

not relevant

## Command used to create docker container (run/create/compose/screenshot)

docker create \
  --name=resilio-sync \
  --network macvlan_net \
  -e PUID=0 \
  -e PGID=0 \
  -e TZ=Europe/London \
  -e UMASK_SET=022 \
  -p 80:8888 \
  -p 55555:55555 \
  -v /docker_mounts/resilio_config:/config \
  -v resilio_downloads:/downloads \
  -v /sharedfolders:/sync \
  --restart unless-stopped \
  --ip=192.168.178.101 \
  linuxserver/resilio-sync

## Docker logs

not relevant

**Comment by aptalca** [comment]
It's listening on `0.0.0.0`: https://github.com/linuxserver/docker-resilio-sync/blob/master/root/defaults/sync.conf#L12

**Comment by malger** [comment]
okay looks right :+1: however I can only reach the container at 8888. I will look at the docker service log later to see if it's really related to the image, let u know then
