### ISSUE TITLE
Using docker-resilio-sync without the GUI

### ISSUE THREAD

**Issue by pascalandy** [linuxserver/docker-resilio-sync#28]
### Question

Is it possible to use this docker image without using the GUI? I'd like to pass a **secret** so I don't have anything else to configure when I start the service.

I [used this image](https://github.com/nimmis/docker-resilio-sync) since a few years, but I now have permissions issues. Some files between my nodes don't have the same permissions and drives me crazy :-p

### per example

```
  docker service create \
    --name ${CTN_resilio2} --hostname ${CTN_resilio2} \
    --network ${NTW_RESILIO} --replicas "1" \
    --restart-condition "any" --restart-max-attempts "20" \
    --reserve-memory "192M" --limit-memory "512M" \
    --limit-cpu "0.333" \
    --constraint 'node.labels.nodeid==2' \
    --publish "33332:33333" \
    -e RSLSYNC_SECRET=$(cat ${secret_token_path}) \
    -e PUID=1000 \
    -e PGID=1000 \
    -e TZ=Europe/London \
    -e UMASK_SET=<022> \
    --mount type=bind,source=${MNT_SOURCE_RESILIO},target=/data \
    ${IMG_resilio}
```

**Comment by ironicbadger** [comment]
What is the purpose of the secret?
