### ISSUE TITLE
Needs more max_user_watches

### ISSUE THREAD

**Issue by spuder** [linuxserver/docker-resilio-sync#32]
When using this container, the default max_watch for inotify is 8192

<img width="521" alt="Screen Shot 2020-12-21 at 9 22 30 PM" src="https://user-images.githubusercontent.com/242382/102848819-feaee500-43d2-11eb-996b-0eafe7b988e2.png">

https://help.resilio.com/hc/en-us/articles/360015593120-Agent-run-out-of-system-notify-watchers-Updated-files-will-be-uploaded-only-after-periodic-folder-rescan#:~:text=Updated%20files%20will%20be%20uploaded%20only%20after%20periodic%20folder%20rescan,-Resilio%20Sync%20uses&text=If%20Sync%20reaches%20the%20system's,folder%2C%20either%20manually%20or%20periodically.

This results in errors like this in the gui

>Agent Run Out Of System Notify Watchers. Updated Files Will Be Uploaded Only After Periodic Folder Rescan

<img width="1225" alt="Screen Shot 2020-12-21 at 9 21 51 PM" src="https://user-images.githubusercontent.com/242382/102848814-fc4c8b00-43d2-11eb-9602-65184d8717f7.png">

It would be nice to increase the default, or atleast make it more easily configurable. The number should be less than or equal to `2147483647`

```
sudo sysctl fs.inotify.max_user_watches= 2147483647
```

**Comment by aptalca** [comment]
Did you try setting the sysctl as a docker argument?

**Comment by Sawtaytoes** [comment]
I'm in a TrueNAS SCALE environment and need access to this value, but the setting is noted as read-only.

Is there an env var I could set instead?

**Comment by aptalca** [comment]
It's a docker argument, not an env variable.

**Comment by Sawtaytoes** [comment]
Ah, you're right. I thought it was just env vars.

How do you set `sysctl` as a Docker arg? Is that `-w`?

**Comment by Sawtaytoes** [comment]
I figured it out. You add this to the host system, and it's available in the Docker container.

**Comment by jere-co** [comment]
> I figured it out. You add this to the host system, and it's available in the Docker container.

Mind sharing the arg?
