### ISSUE TITLE
Can this docker image use alpine as its base image?

### ISSUE THREAD

**Issue by BROBIRD** [linuxserver/docker-resilio-sync#38]
## Desired Behavior
Use `Alpine Linux` as base image
## Current Behavior
Now base image is `Ubuntu`

**Comment by j0nnymoe** [comment]
At least take the time to give a reason why and what benefits you'd feel it would bring.

**Comment by BROBIRD** [comment]
> At least take the time to give a reason why and what benefits you'd feel it would bring.

OK, I want the image size to be as small as possible, so I consider that Alpine Linux may be a good choice.
