### ISSUE TITLE
[FEAT] Release docker image for Resilio Sync 3.0

### ISSUE THREAD

**Issue by Joly0** [linuxserver/docker-resilio-sync#49]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

Update the docker image to use resilio sync 3.0

### Reason for change

Resilio sync 3.0 has been released, but the new versions are not covered by the curl request `curl -sX GET https://linux-packages.resilio.com/resilio-sync/deb/dists/resilio-sync/non-free/binary-amd64/Packages` so it isnt grabbed correctly. There still is a deb file to download and install it https://help.resilio.com/hc/en-us/articles/206178924-Installing-Sync-package-on-Linux

**Comment by Roxedus** [comment]
We need a repository, or some other endpoint to programmatically get new releases from. Getting the release number from html is unreliable

**Comment by Joly0** [comment]
As far as i know, there is none (yet)

**Comment by haroldfinch69** [comment]
I hate to be the bearer of bad news but they have [depreciated support for docker ](https://help.resilio.com/hc/en-us/articles/31386579044755-Resilio-Sync-3-0-change-log).

Can the download endpoint be used? The files are hosted at: ttps://download-cdn.resilio.com/stable/linux/x64/0/resilio-sync_x64.tar.gz

**Comment by Schu-** [comment]
Sigh. This is some sad news......

**Comment by haroldfinch69** [comment]
I agree, however it has forced me to look beyond just the Linuxserver docker-compose file, and it's forced me to create my own dockerfile and image from scratch.   It's been a good learning opportunity!

**Comment by Roxedus** [comment]
> Can the download endpoint be used?

No, we need a programmatic way to get the version number without downloading it, before considering alternate sources.

**Comment by Joly0** [comment]
> > Can the download endpoint be used?
> 
> No, we need a programmatic way to get the version number without downloading it, before considering alternate sources. 

I guess then this container wont receive any more updates as it seems like resilio wont update their usual sources for this

**Comment by aptalca** [comment]
They still have the repo listed as an installation source. The repo has not been updated to host 3.0, but they didn't say that the repo is deprecated. Only the docker method is listed as deprecated here: https://help.resilio.com/hc/en-us/articles/206178924-Installing-Sync-package-on-Linux

**Comment by Joly0** [comment]
Hm, ok. But they havent updated it yet, which is kinda weird imo. But i also noticed, that the binhex docker has already been updated to 3.0. Maybe it might be worth to take a look how they do the check for new versions. Maybe they have found a good method which could be adapted to this one here?

**Comment by Roxedus** [comment]
Binhex' detection does not seem automated

**Comment by WizenThorne** [comment]
So long as syncing doesn't break between 2.8 and 3.0 I'm personally not in any rush to update, but it sounds like there are some transfer rate benefits in 3.0?

Also, the fact that binhex is on 3.0 is great news, as the Docker deprecation was worrisome at first.

Anyway, thank you to the Linuxserver team for all of your hard work!!! ❤️

**Comment by denkristoffer** [comment]
`latest` is pointing to a v3 release now so watch out if you haven't pinned your version yet 😄
