### ISSUE TITLE
[FEAT] Resilio Sync still on a old release

### ISSUE THREAD

**Issue by trigger2k20** [linuxserver/docker-resilio-sync#52]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

hi, 
pulled the image today new: Resilio still on release Version: 3.0.0 (1409) instead of release Version: 3.0.1 (1414) pls. fix

### Reason for change

incompatibilities between releases

### Proposed code change

 update regularly, thanks.

**Comment by thespad** [comment]
We can only build images with the versions the upstream project publishes. When they update their apt repo with the new version, we'll build it.

**Comment by trigger2k20** [comment]
Thanks do you have a Link to their webpage ?
